name: CodSpeed
on:
  push:
    branches:
      - "main"
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backfill builds
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust-benchmarks:
    name: Run Rust benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-codspeed
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-codspeed

      - name: Build the benchmark target(s)
        working-directory: lib
        run: cargo codspeed build

      - name: Run the Rust benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          working-directory: lib
          run: cargo codspeed run
          token: ${{ secrets.CODSPEED_TOKEN }}

  web-benchmarks:
    name: Run web benchmarks
    runs-on: ubuntu-latest
    env:
      RUNNER_VERSION: '0.4.2'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install web dependencies
        working-directory: web
        run: npm ci --legacy-peer-deps

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build lib-wasm package
        working-directory: lib-wasm
        run: wasm-pack build --target web

      - name: Run the web benchmark with CodSpeed
        uses: CodSpeedHQ/action@v3
        with:
          working-directory: web
          run: npm run benchmark
          token: ${{ secrets.CODSPEED_TOKEN }}
