name: CodSpeed

on:
  push:
    branches:
      - "main"
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backfill builds
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  rust-benchmarks:
    name: Run Rust benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-codspeed
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-codspeed

      - name: Build the benchmark target(s)
        working-directory: lib
        run: cargo codspeed build

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          working-directory: lib
          run: cargo codspeed run
          token: ${{ secrets.CODSPEED_TOKEN }}

  wasm-benchmarks:
    name: Run Wasm benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build Wasm module
        working-directory: lib-wasm
        run: wasm-pack build --target web

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'lib-wasm/benchmark/package-lock.json'

      - name: Install dependencies
        working-directory: lib-wasm/benchmark
        run: npm ci

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          working-directory: lib-wasm/benchmark
          mode: simulation
          run: npm run bench
          token: ${{ secrets.CODSPEED_TOKEN }}
