name: Web Lint

on: [pull_request, push]

jobs:
  web_lint:
    name: Web Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Build lib-wasm
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      
      - name: Build wasm package
        working-directory: ./lib-wasm
        run: wasm-pack build --target web

      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint
